// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package ethtool

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// loadEthtool returns the embedded CollectionSpec for ethtool.
func loadEthtool() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_EthtoolBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load ethtool: %w", err)
	}

	return spec, err
}

// loadEthtoolObjects loads ethtool and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*ethtoolObjects
//	*ethtoolPrograms
//	*ethtoolMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadEthtoolObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadEthtool()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// ethtoolSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ethtoolSpecs struct {
	ethtoolProgramSpecs
	ethtoolMapSpecs
}

// ethtoolSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ethtoolProgramSpecs struct {
	KpDevEthtool *ebpf.ProgramSpec `ebpf:"kp_dev_ethtool"`
	KpEthnlDev   *ebpf.ProgramSpec `ebpf:"kp_ethnl_dev"`
	KpEthnlDoit  *ebpf.ProgramSpec `ebpf:"kp_ethnl_doit"`
	KrpEthnlDev  *ebpf.ProgramSpec `ebpf:"krp_ethnl_dev"`
}

// ethtoolMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ethtoolMapSpecs struct {
	Events      *ebpf.MapSpec `ebpf:"events"`
	EventsCache *ebpf.MapSpec `ebpf:"events_cache"`
}

// ethtoolObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadEthtoolObjects or ebpf.CollectionSpec.LoadAndAssign.
type ethtoolObjects struct {
	ethtoolPrograms
	ethtoolMaps
}

func (o *ethtoolObjects) Close() error {
	return _EthtoolClose(
		&o.ethtoolPrograms,
		&o.ethtoolMaps,
	)
}

// ethtoolMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadEthtoolObjects or ebpf.CollectionSpec.LoadAndAssign.
type ethtoolMaps struct {
	Events      *ebpf.Map `ebpf:"events"`
	EventsCache *ebpf.Map `ebpf:"events_cache"`
}

func (m *ethtoolMaps) Close() error {
	return _EthtoolClose(
		m.Events,
		m.EventsCache,
	)
}

// ethtoolPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadEthtoolObjects or ebpf.CollectionSpec.LoadAndAssign.
type ethtoolPrograms struct {
	KpDevEthtool *ebpf.Program `ebpf:"kp_dev_ethtool"`
	KpEthnlDev   *ebpf.Program `ebpf:"kp_ethnl_dev"`
	KpEthnlDoit  *ebpf.Program `ebpf:"kp_ethnl_doit"`
	KrpEthnlDev  *ebpf.Program `ebpf:"krp_ethnl_dev"`
}

func (p *ethtoolPrograms) Close() error {
	return _EthtoolClose(
		p.KpDevEthtool,
		p.KpEthnlDev,
		p.KpEthnlDoit,
		p.KrpEthnlDev,
	)
}

func _EthtoolClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed ethtool_bpfeb.o
var _EthtoolBytes []byte
