// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64

package xdp

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// loadXdptrace returns the embedded CollectionSpec for xdptrace.
func loadXdptrace() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_XdptraceBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load xdptrace: %w", err)
	}

	return spec, err
}

// loadXdptraceObjects loads xdptrace and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*xdptraceObjects
//	*xdptracePrograms
//	*xdptraceMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadXdptraceObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadXdptrace()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// xdptraceSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type xdptraceSpecs struct {
	xdptraceProgramSpecs
	xdptraceMapSpecs
}

// xdptraceSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type xdptraceProgramSpecs struct {
	TracePackets *ebpf.ProgramSpec `ebpf:"trace_packets"`
	XdpF2        *ebpf.ProgramSpec `ebpf:"xdp_f2"`
}

// xdptraceMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type xdptraceMapSpecs struct {
	Events      *ebpf.MapSpec `ebpf:"events"`
	XdpStatsMap *ebpf.MapSpec `ebpf:"xdp_stats_map"`
}

// xdptraceObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadXdptraceObjects or ebpf.CollectionSpec.LoadAndAssign.
type xdptraceObjects struct {
	xdptracePrograms
	xdptraceMaps
}

func (o *xdptraceObjects) Close() error {
	return _XdptraceClose(
		&o.xdptracePrograms,
		&o.xdptraceMaps,
	)
}

// xdptraceMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadXdptraceObjects or ebpf.CollectionSpec.LoadAndAssign.
type xdptraceMaps struct {
	Events      *ebpf.Map `ebpf:"events"`
	XdpStatsMap *ebpf.Map `ebpf:"xdp_stats_map"`
}

func (m *xdptraceMaps) Close() error {
	return _XdptraceClose(
		m.Events,
		m.XdpStatsMap,
	)
}

// xdptracePrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadXdptraceObjects or ebpf.CollectionSpec.LoadAndAssign.
type xdptracePrograms struct {
	TracePackets *ebpf.Program `ebpf:"trace_packets"`
	XdpF2        *ebpf.Program `ebpf:"xdp_f2"`
}

func (p *xdptracePrograms) Close() error {
	return _XdptraceClose(
		p.TracePackets,
		p.XdpF2,
	)
}

func _XdptraceClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed xdptrace_bpfel.o
var _XdptraceBytes []byte
