// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64

package iptables

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// loadIptablestrace returns the embedded CollectionSpec for iptablestrace.
func loadIptablestrace() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_IptablestraceBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load iptablestrace: %w", err)
	}

	return spec, err
}

// loadIptablestraceObjects loads iptablestrace and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*iptablestraceObjects
//	*iptablestracePrograms
//	*iptablestraceMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadIptablestraceObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadIptablestrace()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// iptablestraceSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type iptablestraceSpecs struct {
	iptablestraceProgramSpecs
	iptablestraceMapSpecs
}

// iptablestraceSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type iptablestraceProgramSpecs struct {
	K_iptDoTable *ebpf.ProgramSpec `ebpf:"k_ipt_do_table"`
	K_nfLogTrace *ebpf.ProgramSpec `ebpf:"k_nf_log_trace"`
	K_nftDoChain *ebpf.ProgramSpec `ebpf:"k_nft_do_chain"`
	KrIptDoTable *ebpf.ProgramSpec `ebpf:"kr_ipt_do_table"`
	KrNftDoChain *ebpf.ProgramSpec `ebpf:"kr_nft_do_chain"`
}

// iptablestraceMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type iptablestraceMapSpecs struct {
	Events         *ebpf.MapSpec `ebpf:"events"`
	SkbtracerEvent *ebpf.MapSpec `ebpf:"skbtracer_event"`
	SkbtracerIpt   *ebpf.MapSpec `ebpf:"skbtracer_ipt"`
	SkbtracerStack *ebpf.MapSpec `ebpf:"skbtracer_stack"`
}

// iptablestraceObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadIptablestraceObjects or ebpf.CollectionSpec.LoadAndAssign.
type iptablestraceObjects struct {
	iptablestracePrograms
	iptablestraceMaps
}

func (o *iptablestraceObjects) Close() error {
	return _IptablestraceClose(
		&o.iptablestracePrograms,
		&o.iptablestraceMaps,
	)
}

// iptablestraceMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadIptablestraceObjects or ebpf.CollectionSpec.LoadAndAssign.
type iptablestraceMaps struct {
	Events         *ebpf.Map `ebpf:"events"`
	SkbtracerEvent *ebpf.Map `ebpf:"skbtracer_event"`
	SkbtracerIpt   *ebpf.Map `ebpf:"skbtracer_ipt"`
	SkbtracerStack *ebpf.Map `ebpf:"skbtracer_stack"`
}

func (m *iptablestraceMaps) Close() error {
	return _IptablestraceClose(
		m.Events,
		m.SkbtracerEvent,
		m.SkbtracerIpt,
		m.SkbtracerStack,
	)
}

// iptablestracePrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadIptablestraceObjects or ebpf.CollectionSpec.LoadAndAssign.
type iptablestracePrograms struct {
	K_iptDoTable *ebpf.Program `ebpf:"k_ipt_do_table"`
	K_nfLogTrace *ebpf.Program `ebpf:"k_nf_log_trace"`
	K_nftDoChain *ebpf.Program `ebpf:"k_nft_do_chain"`
	KrIptDoTable *ebpf.Program `ebpf:"kr_ipt_do_table"`
	KrNftDoChain *ebpf.Program `ebpf:"kr_nft_do_chain"`
}

func (p *iptablestracePrograms) Close() error {
	return _IptablestraceClose(
		p.K_iptDoTable,
		p.K_nfLogTrace,
		p.K_nftDoChain,
		p.KrIptDoTable,
		p.KrNftDoChain,
	)
}

func _IptablestraceClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed iptablestrace_bpfel.o
var _IptablestraceBytes []byte
