// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package nftables

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type nftabletraceTraceInfo struct {
	Id          uint32
	Type        uint32
	TableName   [64]uint8
	TableHandle uint64
	ChainName   [64]uint8
	ChainHandle uint64
	RuleHandle  uint64
	JumpTarget  [64]uint8
	Verdict     uint32
	Family      int32
	Nfproto     uint8
	Policy      uint8
	Len         uint16
	Mark        uint32
	Iif         uint32
	Oif         uint32
	IifType     uint16
	OifType     uint16
	IifName     [16]uint8
	OifName     [16]uint8
	IpInfo      struct {
		SrcPort uint16
		DstPort uint16
		SrcIp4  uint32
		DstIp4  uint32
		SrcIp6  struct{ In6U struct{ U6Addr8 [16]uint8 } }
		DstIp6  struct{ In6U struct{ U6Addr8 [16]uint8 } }
		SrcMac  [6]uint8
		DstMac  [6]uint8
		IpProto uint8
		_       [3]byte
	}
	Time    uint64
	Counter uint64
	Process struct {
		Name [64]int8
		Pid  uint32
	}
	_ [4]byte
}

// loadNftabletrace returns the embedded CollectionSpec for nftabletrace.
func loadNftabletrace() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_NftabletraceBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load nftabletrace: %w", err)
	}

	return spec, err
}

// loadNftabletraceObjects loads nftabletrace and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*nftabletraceObjects
//	*nftabletracePrograms
//	*nftabletraceMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadNftabletraceObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadNftabletrace()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// nftabletraceSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type nftabletraceSpecs struct {
	nftabletraceProgramSpecs
	nftabletraceMapSpecs
}

// nftabletraceSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type nftabletraceProgramSpecs struct {
	KprobeNftTracePacket *ebpf.ProgramSpec `ebpf:"kprobe_nft_trace_packet"`
}

// nftabletraceMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type nftabletraceMapSpecs struct {
	Events     *ebpf.MapSpec `ebpf:"events"`
	PktCounter *ebpf.MapSpec `ebpf:"pkt_counter"`
	SampleRate *ebpf.MapSpec `ebpf:"sample_rate"`
}

// nftabletraceObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadNftabletraceObjects or ebpf.CollectionSpec.LoadAndAssign.
type nftabletraceObjects struct {
	nftabletracePrograms
	nftabletraceMaps
}

func (o *nftabletraceObjects) Close() error {
	return _NftabletraceClose(
		&o.nftabletracePrograms,
		&o.nftabletraceMaps,
	)
}

// nftabletraceMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadNftabletraceObjects or ebpf.CollectionSpec.LoadAndAssign.
type nftabletraceMaps struct {
	Events     *ebpf.Map `ebpf:"events"`
	PktCounter *ebpf.Map `ebpf:"pkt_counter"`
	SampleRate *ebpf.Map `ebpf:"sample_rate"`
}

func (m *nftabletraceMaps) Close() error {
	return _NftabletraceClose(
		m.Events,
		m.PktCounter,
		m.SampleRate,
	)
}

// nftabletracePrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadNftabletraceObjects or ebpf.CollectionSpec.LoadAndAssign.
type nftabletracePrograms struct {
	KprobeNftTracePacket *ebpf.Program `ebpf:"kprobe_nft_trace_packet"`
}

func (p *nftabletracePrograms) Close() error {
	return _NftabletraceClose(
		p.KprobeNftTracePacket,
	)
}

func _NftabletraceClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed nftabletrace_bpfeb.o
var _NftabletraceBytes []byte
