// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64

package nftables

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type nftabletraceTraceInfo struct {
	SkbHash uint32
	SkInfo  struct {
		SkId         uint64
		RxDstIfindex uint32
		BacklogLen   uint32
		RcvBuff      uint32
		SndBuff      uint32
		Priority     uint32
		Mark         uint32
		Type         uint16
		Pad          uint16
	}
	DevInfo struct {
		IifName [16]uint8
		OifName [16]uint8
		Iif     uint32
		Oif     uint32
		IifType uint16
		OifType uint16
		Pad     [2]uint16
	}
	NftInfo struct {
		Type            uint32
		Verdict         uint32
		TableName       [64]uint8
		TableHandle     uint64
		ChainName       [64]uint8
		ChainHandle     uint64
		RuleHandle      uint64
		JumpTarget      [64]uint8
		NfProto         uint8
		Policy          uint8
		Len             uint16
		Mark            uint32
		BaseChainFamily uint32
		_               [4]byte
	}
	ConnInfo struct {
		C_mac      [6]uint8
		D_mac      [6]uint8
		C_port     uint16
		S_port     uint16
		C_ip       uint32
		S_ip       uint32
		C_ip6      struct{ In6U struct{ U6Addr8 [16]uint8 } }
		S_ip6      struct{ In6U struct{ U6Addr8 [16]uint8 } }
		NetNs      uint32
		Family     uint8
		Protocol   uint8
		SkProtocol uint16
		Seq        uint16
		OldState   uint8
		NewState   uint8
		IcmpInfo   struct {
			Type uint8
			Code uint8
		}
		Role uint8
		_    [1]byte
	}
	ProcessInfo struct {
		Name [64]uint8
		Pid  uint64
		Tgid uint64
	}
}

// loadNftabletrace returns the embedded CollectionSpec for nftabletrace.
func loadNftabletrace() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_NftabletraceBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load nftabletrace: %w", err)
	}

	return spec, err
}

// loadNftabletraceObjects loads nftabletrace and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*nftabletraceObjects
//	*nftabletracePrograms
//	*nftabletraceMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadNftabletraceObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadNftabletrace()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// nftabletraceSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type nftabletraceSpecs struct {
	nftabletraceProgramSpecs
	nftabletraceMapSpecs
}

// nftabletraceSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type nftabletraceProgramSpecs struct {
	FentryNftDoChain     *ebpf.ProgramSpec `ebpf:"fentry_nft_do_chain"`
	KprobeNftTracePacket *ebpf.ProgramSpec `ebpf:"kprobe_nft_trace_packet"`
}

// nftabletraceMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type nftabletraceMapSpecs struct {
	Events *ebpf.MapSpec `ebpf:"events"`
}

// nftabletraceObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadNftabletraceObjects or ebpf.CollectionSpec.LoadAndAssign.
type nftabletraceObjects struct {
	nftabletracePrograms
	nftabletraceMaps
}

func (o *nftabletraceObjects) Close() error {
	return _NftabletraceClose(
		&o.nftabletracePrograms,
		&o.nftabletraceMaps,
	)
}

// nftabletraceMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadNftabletraceObjects or ebpf.CollectionSpec.LoadAndAssign.
type nftabletraceMaps struct {
	Events *ebpf.Map `ebpf:"events"`
}

func (m *nftabletraceMaps) Close() error {
	return _NftabletraceClose(
		m.Events,
	)
}

// nftabletracePrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadNftabletraceObjects or ebpf.CollectionSpec.LoadAndAssign.
type nftabletracePrograms struct {
	FentryNftDoChain     *ebpf.Program `ebpf:"fentry_nft_do_chain"`
	KprobeNftTracePacket *ebpf.Program `ebpf:"kprobe_nft_trace_packet"`
}

func (p *nftabletracePrograms) Close() error {
	return _NftabletraceClose(
		p.FentryNftDoChain,
		p.KprobeNftTracePacket,
	)
}

func _NftabletraceClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed nftabletrace_bpfel.o
var _NftabletraceBytes []byte
