// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64

package tcp

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// loadTcpconn returns the embedded CollectionSpec for tcpconn.
func loadTcpconn() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_TcpconnBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load tcpconn: %w", err)
	}

	return spec, err
}

// loadTcpconnObjects loads tcpconn and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*tcpconnObjects
//	*tcpconnPrograms
//	*tcpconnMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadTcpconnObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadTcpconn()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// tcpconnSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tcpconnSpecs struct {
	tcpconnProgramSpecs
	tcpconnMapSpecs
}

// tcpconnSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tcpconnProgramSpecs struct {
	FentrySysAccept4        *ebpf.ProgramSpec `ebpf:"fentry___sys_accept4"`
	FentrySysConnect        *ebpf.ProgramSpec `ebpf:"fentry___sys_connect"`
	FentrySysConnectFile    *ebpf.ProgramSpec `ebpf:"fentry___sys_connect_file"`
	FexitSysAccept4         *ebpf.ProgramSpec `ebpf:"fexit___sys_accept4"`
	FexitSysConnect         *ebpf.ProgramSpec `ebpf:"fexit___sys_connect"`
	K_icskCompleteHashdance *ebpf.ProgramSpec `ebpf:"k_icsk_complete_hashdance"`
	K_tcpConnect            *ebpf.ProgramSpec `ebpf:"k_tcp_connect"`
	TpInetSockSetState      *ebpf.ProgramSpec `ebpf:"tp_inet_sock_set_state"`
}

// tcpconnMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tcpconnMapSpecs struct {
	Events    *ebpf.MapSpec `ebpf:"events"`
	FdInfoMap *ebpf.MapSpec `ebpf:"fd_info_map"`
	Progs     *ebpf.MapSpec `ebpf:"progs"`
	Socks     *ebpf.MapSpec `ebpf:"socks"`
}

// tcpconnObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadTcpconnObjects or ebpf.CollectionSpec.LoadAndAssign.
type tcpconnObjects struct {
	tcpconnPrograms
	tcpconnMaps
}

func (o *tcpconnObjects) Close() error {
	return _TcpconnClose(
		&o.tcpconnPrograms,
		&o.tcpconnMaps,
	)
}

// tcpconnMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadTcpconnObjects or ebpf.CollectionSpec.LoadAndAssign.
type tcpconnMaps struct {
	Events    *ebpf.Map `ebpf:"events"`
	FdInfoMap *ebpf.Map `ebpf:"fd_info_map"`
	Progs     *ebpf.Map `ebpf:"progs"`
	Socks     *ebpf.Map `ebpf:"socks"`
}

func (m *tcpconnMaps) Close() error {
	return _TcpconnClose(
		m.Events,
		m.FdInfoMap,
		m.Progs,
		m.Socks,
	)
}

// tcpconnPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadTcpconnObjects or ebpf.CollectionSpec.LoadAndAssign.
type tcpconnPrograms struct {
	FentrySysAccept4        *ebpf.Program `ebpf:"fentry___sys_accept4"`
	FentrySysConnect        *ebpf.Program `ebpf:"fentry___sys_connect"`
	FentrySysConnectFile    *ebpf.Program `ebpf:"fentry___sys_connect_file"`
	FexitSysAccept4         *ebpf.Program `ebpf:"fexit___sys_accept4"`
	FexitSysConnect         *ebpf.Program `ebpf:"fexit___sys_connect"`
	K_icskCompleteHashdance *ebpf.Program `ebpf:"k_icsk_complete_hashdance"`
	K_tcpConnect            *ebpf.Program `ebpf:"k_tcp_connect"`
	TpInetSockSetState      *ebpf.Program `ebpf:"tp_inet_sock_set_state"`
}

func (p *tcpconnPrograms) Close() error {
	return _TcpconnClose(
		p.FentrySysAccept4,
		p.FentrySysConnect,
		p.FentrySysConnectFile,
		p.FexitSysAccept4,
		p.FexitSysConnect,
		p.K_icskCompleteHashdance,
		p.K_tcpConnect,
		p.TpInetSockSetState,
	)
}

func _TcpconnClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed tcpconn_bpfel.o
var _TcpconnBytes []byte
