// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64

package tcp

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type tcpconnEventT struct {
	CurTime uint64
	Skc     struct {
		State        uint8
		ReusePort    uint8
		Pad          [2]uint8
		BoundIfindex uint32
	}
	SkInfo struct {
		SkId         uint64
		RxDstIfindex uint32
		BacklogLen   uint32
		RcvBuff      uint32
		SndBuff      uint32
		Priority     uint32
		Mark         uint32
		Type         uint16
		Pad          uint16
	}
	SocketInfo struct {
		SocketId  uint64
		State     uint16
		Type      uint16
		Pad       uint32
		FileInode uint64
		Flags     uint64
	}
	ConnInfo struct {
		C_mac      [6]uint8
		D_mac      [6]uint8
		C_port     uint16
		S_port     uint16
		C_ip       uint32
		S_ip       uint32
		C_ip6      struct{ In6U struct{ U6Addr8 [16]uint8 } }
		S_ip6      struct{ In6U struct{ U6Addr8 [16]uint8 } }
		NetNs      uint32
		Family     uint8
		Protocol   uint8
		SkProtocol uint16
		Seq        uint16
		OldState   uint8
		NewState   uint8
		IcmpInfo   struct {
			Type uint8
			Code uint8
		}
		Role uint8
		_    [1]byte
	}
	_       [4]byte
	Process struct {
		Name [64]uint8
		Pid  uint64
		Tgid uint64
	}
}

// loadTcpconn returns the embedded CollectionSpec for tcpconn.
func loadTcpconn() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_TcpconnBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load tcpconn: %w", err)
	}

	return spec, err
}

// loadTcpconnObjects loads tcpconn and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*tcpconnObjects
//	*tcpconnPrograms
//	*tcpconnMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadTcpconnObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadTcpconn()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// tcpconnSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tcpconnSpecs struct {
	tcpconnProgramSpecs
	tcpconnMapSpecs
}

// tcpconnSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tcpconnProgramSpecs struct {
	FentrySysAccept4     *ebpf.ProgramSpec `ebpf:"fentry___sys_accept4"`
	FentrySysConnect     *ebpf.ProgramSpec `ebpf:"fentry___sys_connect"`
	FentrySysConnectFile *ebpf.ProgramSpec `ebpf:"fentry___sys_connect_file"`
	FentryTcpV4Connect   *ebpf.ProgramSpec `ebpf:"fentry_tcp_v4_connect"`
	FentryTcpV6Connect   *ebpf.ProgramSpec `ebpf:"fentry_tcp_v6_connect"`
	FexitSysAccept4      *ebpf.ProgramSpec `ebpf:"fexit___sys_accept4"`
	FexitSysConnect      *ebpf.ProgramSpec `ebpf:"fexit___sys_connect"`
	FexitDoAccept        *ebpf.ProgramSpec `ebpf:"fexit_do_accept"`
	FexitInetCskAccept   *ebpf.ProgramSpec `ebpf:"fexit_inet_csk_accept"`
	K_setState           *ebpf.ProgramSpec `ebpf:"k_set_state"`
	K_tcpV4DestroySock   *ebpf.ProgramSpec `ebpf:"k_tcp_v4_destroy_sock"`
	RtpTcpDestroySock    *ebpf.ProgramSpec `ebpf:"rtp_tcp_destroy_sock"`
	TcpCloseEntry        *ebpf.ProgramSpec `ebpf:"tcp_close_entry"`
	TpDestroySockFunc    *ebpf.ProgramSpec `ebpf:"tp_destroy_sock_func"`
}

// tcpconnMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tcpconnMapSpecs struct {
	Events        *ebpf.MapSpec `ebpf:"events"`
	FdInfoMap     *ebpf.MapSpec `ebpf:"fd_info_map"`
	PrintStackMap *ebpf.MapSpec `ebpf:"print_stack_map"`
	SockLinkType  *ebpf.MapSpec `ebpf:"sock_link_type"`
}

// tcpconnObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadTcpconnObjects or ebpf.CollectionSpec.LoadAndAssign.
type tcpconnObjects struct {
	tcpconnPrograms
	tcpconnMaps
}

func (o *tcpconnObjects) Close() error {
	return _TcpconnClose(
		&o.tcpconnPrograms,
		&o.tcpconnMaps,
	)
}

// tcpconnMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadTcpconnObjects or ebpf.CollectionSpec.LoadAndAssign.
type tcpconnMaps struct {
	Events        *ebpf.Map `ebpf:"events"`
	FdInfoMap     *ebpf.Map `ebpf:"fd_info_map"`
	PrintStackMap *ebpf.Map `ebpf:"print_stack_map"`
	SockLinkType  *ebpf.Map `ebpf:"sock_link_type"`
}

func (m *tcpconnMaps) Close() error {
	return _TcpconnClose(
		m.Events,
		m.FdInfoMap,
		m.PrintStackMap,
		m.SockLinkType,
	)
}

// tcpconnPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadTcpconnObjects or ebpf.CollectionSpec.LoadAndAssign.
type tcpconnPrograms struct {
	FentrySysAccept4     *ebpf.Program `ebpf:"fentry___sys_accept4"`
	FentrySysConnect     *ebpf.Program `ebpf:"fentry___sys_connect"`
	FentrySysConnectFile *ebpf.Program `ebpf:"fentry___sys_connect_file"`
	FentryTcpV4Connect   *ebpf.Program `ebpf:"fentry_tcp_v4_connect"`
	FentryTcpV6Connect   *ebpf.Program `ebpf:"fentry_tcp_v6_connect"`
	FexitSysAccept4      *ebpf.Program `ebpf:"fexit___sys_accept4"`
	FexitSysConnect      *ebpf.Program `ebpf:"fexit___sys_connect"`
	FexitDoAccept        *ebpf.Program `ebpf:"fexit_do_accept"`
	FexitInetCskAccept   *ebpf.Program `ebpf:"fexit_inet_csk_accept"`
	K_setState           *ebpf.Program `ebpf:"k_set_state"`
	K_tcpV4DestroySock   *ebpf.Program `ebpf:"k_tcp_v4_destroy_sock"`
	RtpTcpDestroySock    *ebpf.Program `ebpf:"rtp_tcp_destroy_sock"`
	TcpCloseEntry        *ebpf.Program `ebpf:"tcp_close_entry"`
	TpDestroySockFunc    *ebpf.Program `ebpf:"tp_destroy_sock_func"`
}

func (p *tcpconnPrograms) Close() error {
	return _TcpconnClose(
		p.FentrySysAccept4,
		p.FentrySysConnect,
		p.FentrySysConnectFile,
		p.FentryTcpV4Connect,
		p.FentryTcpV6Connect,
		p.FexitSysAccept4,
		p.FexitSysConnect,
		p.FexitDoAccept,
		p.FexitInetCskAccept,
		p.K_setState,
		p.K_tcpV4DestroySock,
		p.RtpTcpDestroySock,
		p.TcpCloseEntry,
		p.TpDestroySockFunc,
	)
}

func _TcpconnClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed tcpconn_bpfel.o
var _TcpconnBytes []byte
