// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// loadSysctl returns the embedded CollectionSpec for sysctl.
func loadSysctl() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_SysctlBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load sysctl: %w", err)
	}

	return spec, err
}

// loadSysctlObjects loads sysctl and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*sysctlObjects
//	*sysctlPrograms
//	*sysctlMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadSysctlObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadSysctl()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// sysctlSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type sysctlSpecs struct {
	sysctlProgramSpecs
	sysctlMapSpecs
}

// sysctlSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type sysctlProgramSpecs struct {
	FexitDevinetConfProc      *ebpf.ProgramSpec `ebpf:"fexit_devinet_conf_proc"`
	FexitDevinetSysctlForward *ebpf.ProgramSpec `ebpf:"fexit_devinet_sysctl_forward"`
	FexitIpv4DointAndFlush    *ebpf.ProgramSpec `ebpf:"fexit_ipv4_doint_and_flush"`
}

// sysctlMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type sysctlMapSpecs struct {
	Events *ebpf.MapSpec `ebpf:"events"`
}

// sysctlObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadSysctlObjects or ebpf.CollectionSpec.LoadAndAssign.
type sysctlObjects struct {
	sysctlPrograms
	sysctlMaps
}

func (o *sysctlObjects) Close() error {
	return _SysctlClose(
		&o.sysctlPrograms,
		&o.sysctlMaps,
	)
}

// sysctlMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadSysctlObjects or ebpf.CollectionSpec.LoadAndAssign.
type sysctlMaps struct {
	Events *ebpf.Map `ebpf:"events"`
}

func (m *sysctlMaps) Close() error {
	return _SysctlClose(
		m.Events,
	)
}

// sysctlPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadSysctlObjects or ebpf.CollectionSpec.LoadAndAssign.
type sysctlPrograms struct {
	FexitDevinetConfProc      *ebpf.Program `ebpf:"fexit_devinet_conf_proc"`
	FexitDevinetSysctlForward *ebpf.Program `ebpf:"fexit_devinet_sysctl_forward"`
	FexitIpv4DointAndFlush    *ebpf.Program `ebpf:"fexit_ipv4_doint_and_flush"`
}

func (p *sysctlPrograms) Close() error {
	return _SysctlClose(
		p.FexitDevinetConfProc,
		p.FexitDevinetSysctlForward,
		p.FexitIpv4DointAndFlush,
	)
}

func _SysctlClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed sysctl_bpfel.o
var _SysctlBytes []byte
